### ISSUE TITLE
why CacheRoute dosn't cache in a Switch?

### ISSUE THREAD

**Issue by tuliprope** [CJY0208/react-router-cache-route#1]
why CacheRoute dosn't cache in a Switch?

**Comment by CJY0208** [comment]
**Controlling Render Behavior** is the key of  `CacheRoute` .

In `render` method of `Switch` you can see that there is no any way to do this because `Switch` would **ONLY** render matched route, treating unmatched route as `null` means that `CacheRoute` would be removed either.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L41-L70

PS: 英语不好不要太过为难我...

**Comment by tuliprope** [comment]
我在react-router的基础上改写了Switch,修改了CacheRoute,可以接受visible属性,目前可以使用CacheSwitch实现Switch Cache.
`

  render() {
    const { route } = this.context.router;
    const { children } = this.props;
    const location = this.props.location || route.location;

    children = Array.isArray(children) ? children : [children];
    let match;
    let index = children.findIndex((c) => {
      const {
        path: pathProp,
        exact,
        strict,
        sensitive,
        from
      } = c.props;
      const path = pathProp || from;
      match = matchPath(
        location.pathname,
        { path, exact, strict, sensitive },
        route.match
      );
      return match;
    })

    return children.map((c, i) => {
      if (i === index) {
        if (c.type === CacheRoute)
          return React.cloneElement(c, { location, computedMatch: match, key: i, hidden: false })
        return React.cloneElement(c, { location, computedMatch: match })
      }
      else {
        if (c.type === CacheRoute)
          return React.cloneElement(c, { hidden: true, key: i })
        return null;
      }
    })
}
`
`另外，CacheComponent如果不能match,子组件就会得到空的match(如果子组件依赖match,有可能出错)，所以我将旧match存储起来，如果CacheComponent不能match,就使用旧match.
另外，目前的问题是，CacheRoute不能接受render.



[route-cache.zip](https://github.com/CJY0208/react-router-cache-route/files/2169947/route-cache.zip)

**Comment by CJY0208** [comment]
适配 `Switch` 和扩展 `CacheRoute` 的 `render` props 确实是可以做的事情

但其实 `CacheSwitch` 内部没有必要再去决定组件的 hidden 状态，因为 `CacheComponent` 已经做了这个事情，再做一次判断显得有些多余，也不符合模块职责单一的思想

`Switch` 的问题在于它直接删除了不匹配的组件，我们对它简单动刀，让它面对不匹配的 `CacheRoute` 时仅如实传递 match 结果就好，剩下的事情应该由 `CacheRoute` 独立完成

另外非 matched 状态下使用旧的 match props 我认为不太妥当，可能会造成一些奇怪的问题，我认为我们应该尽可能遵从原汁原味的 `react-router`，不应对这个过程加以干涉，毕竟 `Route` children props 作为函数使用的时候，也是有可能出现不匹配状态下 match 为 null 但组件并未销毁，生命周期还在运转的情况，在此状态下造成的后果应由用户自己承担

我们可以在说明中给出提示，这就够了

**Comment by CJY0208** [comment]
@tuliprope 更新了如下功能
- CacheSwitch
- 非 matched 状态下对应组件不更新，match 值为旧值（其实只是不会更新）
- CacheRoute 的 render、children prop
- CacheRoute 可选缓存时机 [ `forward`, `back`, `always` ]
- 兼容 React 16.3 以下版本（componentWillReceiveProps）
