### ISSUE TITLE
cache do not work?

### ISSUE THREAD

**Issue by lemondreamtobe** [CJY0208/react-router-cache-route#106]
![image](https://user-images.githubusercontent.com/22766436/117431606-058e5c80-af5c-11eb-846c-308f6206e3e2.png)
![image](https://user-images.githubusercontent.com/22766436/117431665-13dc7880-af5c-11eb-914d-540bd0436257.png)
用了之后 所有的路由切换 都是外面包了一层div 没有出现style display none
然后也没有任何的缓存 每次路由切换都得重来

**Comment by CJY0208** [comment]
代码中没看出问题，问题在别处，是否能提供完整的用例？

**Comment by lemondreamtobe** [comment]
> 代码中没看出问题，问题在别处，是否能提供完整的用例？

我也不知道为啥，我把when设置成了always就可以了，默认的那个forward就不行

**Comment by CJY0208** [comment]
可能是路由跳转方式的问题，没问题就先关了~
