### ISSUE TITLE
dropByCacheKey 需要同步操作

### ISSUE THREAD

**Issue by m17805804790** [CJY0208/react-router-cache-route#109]
目前由于dropByCacheKey内部使用this.setState,导致了异步的问题,目前已经fork了代码并且此方法传入callBack进行同步操作,是否需要提交pr

**Comment by m17805804790** [comment]
另外其他的命令式操作是否也需要加入回调函数

**Comment by CJY0208** [comment]
原则上不再建议使用 callback，如果 PR 的话可以是 promise 形式
