### ISSUE TITLE
useDidRecover回调里面如何拿到最新的state

### ISSUE THREAD

**Issue by xiasiyong** [CJY0208/react-router-cache-route#115]
![image](https://user-images.githubusercontent.com/71644769/121470616-0e59ce80-c9f1-11eb-8b72-626a1cabe733.png)
视图里面的cocunt已经变成5了，但是在useDidRecover打印出来的还是0

**Comment by xiasiyong** [comment]
场景：
订单列表页跳过筛选条件搜索出订单
从列表页跳转到订单详情页，编辑完之后返回
需要保留之前的筛选条件，并且刷新列表的数据
我在useDidRecover里面，拿不到之前的筛选状态

**Comment by CJY0208** [comment]
cache-router 版本换成 v1.11.1，然后增加 deps 试试，如下

```jsx
useDidRecover(..., [count])
```

**Comment by nainai-wdd** [comment]
useDidRecover(()=>console.log(count), [count])

**Comment by nainai-wdd** [comment]
useDidRecover(()=>console.log(count), [count])
所需要的state列表，放到第二个数组参数里

**Comment by live680g** [comment]
> useDidRecover(()=>console.log(count), [count]) 所需要的state列表，放到第二个数组参数里

solved problem in this way, thx.

**Comment by live680g** [comment]
> useDidRecover(()=>console.log(count), [count]) 所需要的state列表，放到第二个数组参数里

solved problem in this way, thx.
