### ISSUE TITLE
Bottom navigation

### ISSUE THREAD

**Issue by merganon** [CJY0208/react-router-cache-route#119]
Hi, thanks for your work.

When using a bottom navigation bar I've noticed that the tabs seem to jump around after you click on them.

I have setup a CodeSandbox:
https://codesandbox.io/s/sleepy-platform-r1k41?file=/src/App.js
https://csb-r1k41.netlify.app/

How do I fix that?

**Comment by CJY0208** [comment]
you should use only one `<BottomNavBar />` but not anyother bar in each pages

![image](https://user-images.githubusercontent.com/18415774/125549651-c969f062-303b-4399-bf3d-a5ced706f51b.png)

**Comment by merganon** [comment]
Awesome 🙏 Thank you so much
