### ISSUE TITLE
ts类型校验似乎是有问题

### ISSUE THREAD

**Issue by riminggit** [CJY0208/react-router-cache-route#122]
没有与此调用匹配的重载。
  第 1 个重载(共 2 个)，“(props: CacheRouteProps | Readonly<CacheRouteProps>): CacheRoute”，出现以下错误。
    不能将类型“{ key: string; path: string; cacheKey: string; component: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<CacheRoute> & Readonly<CacheRouteProps> & Readonly<...>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<CacheRoute> & Readonly<CacheRouteProps> & Readonly<...>”上不存在属性“path”。
  第 2 个重载(共 2 个)，“(props: CacheRouteProps, context: any): CacheRoute”，出现以下错误。
    不能将类型“{ key: string; path: string; cacheKey: string; component: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<CacheRoute> & Readonly<CacheRouteProps> & Readonly<...>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<CacheRoute> & Readonly<CacheRouteProps> & Readonly<...>”上不存在属性“path”。ts(2769)
(JSX attribute) path: string

**Comment by ylwbl** [comment]
react-router-dom的版本问题  在版本5.x中 RouteProps 已经没有了  在CacheRoute中extends RouteProps的时候为空,所以会有这个问题。着急可以先使用// @ts-nocheck进行解决

**Comment by ylwbl** [comment]
> 没有与此调用匹配的重载。
> 第 1 个重载(共 2 个)，“(props: CacheRouteProps | Readonly): CacheRoute”，出现以下错误。
> 不能将类型“{ key: string; path: string; cacheKey: string; component: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>”。
> 类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>”上不存在属性“path”。
> 第 2 个重载(共 2 个)，“(props: CacheRouteProps, context: any): CacheRoute”，出现以下错误。
> 不能将类型“{ key: string; path: string; cacheKey: string; component: any; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>”。
> 类型“IntrinsicAttributes & IntrinsicClassAttributes & Readonly & Readonly<...>”上不存在属性“path”。ts(2769)
> (JSX attribute) path: string

yarn add @types/react-router-dom -D 可以解决问题

**Comment by ylwbl** [comment]
react-router-dom 本身并没有提供ts支持

**Comment by riminggit** [comment]
感谢
