### ISSUE TITLE
可以属性控制去掉CacheRoute渲染出来的div节点吗？

### ISSUE THREAD

**Issue by vivianus-chan** [CJY0208/react-router-cache-route#124]
![1629252981(1)](https://user-images.githubusercontent.com/16096294/129825916-d958c784-f07e-40cc-af7e-15edaaefbf62.jpg)

**Comment by CJY0208** [comment]
这层 div 是用来统一增加 display: none 属性的，去掉的话就隐藏不了东西了，可以考虑用属性控制它是 div 还是 span 之类的

**Comment by TwilightOwl** [comment]
Yeah! This extra div element breaks component's layout in my case :(

**Comment by CJY0208** [comment]
@TwilightOwl use `className` prop to fix your style

```jsx
<CacheRoute className="custom-class" />
```

**Comment by CJY0208** [comment]
closed
