### ISSUE TITLE
不适配react-dom和react v17版本

### ISSUE THREAD

**Issue by zhoujiae** [CJY0208/react-router-cache-route#126]
react-dom和react v17版本使用react-router-cache-route报错
You should not use <withRouter(CacheSwitch) /> outside a <Router>

**Comment by ylwbl** [comment]
> react-dom和react v17版本使用react-router-cache-route报错
> You should not use <withRouter(CacheSwitch) /> outside a

这个问题和这个库无关,只是withRouter需要在Router外面使用吧

**Comment by zhoujiae** [comment]
我确实是这样做的，但还是提示错误，安装react v16版本不会报错

**Comment by CJY0208** [comment]
可能是不同 react-router 的版本共存导致的，和库无关，需要注意检查一下是否存在多个 react-router 版本，先关了
