### ISSUE TITLE
怎么动态设置cacheKey的值？

### ISSUE THREAD

**Issue by SKNlEI** [CJY0208/react-router-cache-route#127]
比如我同一个路由，但是路由上不同的查询参数
/test?id=10和/test?id=50 
我想两个都缓存的话应该怎么处理呀？请教大佬

**Comment by CJY0208** [comment]
这样子试试，cacheKey 可以是函数，函数参数是 CacheRoute 内部 CacheComponent 获得的 props
<CacheRoute cacheKey={(props) => `test?${props.location.search}`} />

**Comment by SKNlEI** [comment]
感谢，已经使用这个方法实现了，感谢
