### ISSUE TITLE
Uncaught Invariant Violation

### ISSUE THREAD

**Issue by cendy-z** [CJY0208/react-router-cache-route#13]
Uncaught Invariant Violation: CacheSwitch.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

用router组件的时候是好的，用cacheSwitch就会报错，知道原因么

**Comment by CJY0208** [comment]
@cendy-z 修正了对 React 版本的兼容问题，v1.4.0 版本兼容性调整为 v15+
