### ISSUE TITLE
1.12.1版本配合使用antd3.x版本，会导致下拉框、confirm、message等悬浮相关的组件，切换菜单后悬浮不消失

### ISSUE THREAD

**Issue by FlyCloud1006** [CJY0208/react-router-cache-route#138]

**Comment by CJY0208** [comment]
OK，大致了解了原因，是 react-freeze 所致，我看看怎么修复

**Comment by Rashomon511** [comment]
> OK，大致了解了原因，是 react-freeze 所致，我看看怎么修复

请问这个问题修复了吗？目前同样遇到该问题

**Comment by CJY0208** [comment]
@Rashomon511 应该是修复了的，现在还遇到的话，可以描述一下场景吗？最好能提供 demo

**Comment by Rashomon511** [comment]
> @Rashomon511 应该是修复了的，现在还遇到的话，可以描述一下场景吗？最好能提供 demo
问题一：在使用内部团队的组件库时，下拉框、confirm、message等悬浮相关的组件，在切换菜单时悬浮组件不会消失
问题二： 目前只能安装到1.12.1版本，安装不了最新版本？请问是何缘故

**Comment by CJY0208** [comment]
已经发布到 1.12.6 版本了，需要检查一下你们是否锁了版本

**Comment by Rashomon511** [comment]
> 已经发布到 1.12.6 版本了，需要检查一下你们是否锁了版本
问题已解决，感谢回复

**Comment by CJY0208** [comment]
@Rashomon511 可以正常关闭了对嘛？那这个 issue 我关了

**Comment by Rashomon511** [comment]
> @Rashomon511 可以正常关闭了对嘛？那这个 issue 我关了

可以正常关闭了
