### ISSUE TITLE
同一个页面跳转

### ISSUE THREAD

**Issue by Liuminke1996** [CJY0208/react-router-cache-route#139]
url地址改变了 但是没有执行useDidRecover

**Comment by CJY0208** [comment]
是说同一个 Route 但参数不同吗？尝试借助 multiple 参数来在同一个 Route 中保存多份缓存，具体参考以下表格中的内容

https://github.com/CJY0208/react-router-cache-route#cacheroute-props

**Comment by Liuminke1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
