### ISSUE TITLE
如果路由是通配符匹配的话，只会保留一个路由的缓存，这个问题怎么解决？

### ISSUE THREAD

**Issue by ZhiRongYuan** [CJY0208/react-router-cache-route#14]

**Comment by CJY0208** [comment]
需要提供更具体的信息或 demo 哦

**Comment by ZhiRongYuan** [comment]
> 需要提供更具体的信息或 demo 哦
比方说，这是router规则
 {
      path: '/entcomm/:entityId/:recordId/activities',
      models: () => [import('../models/entcomm/entcommActivities.js')],
      component: () => import('../routes/entcomm/entcommActivities')
    },
    {
      path: '/entcomm/:entityId/:recordId/detail',
      models: () => [import('../models/entcomm/entcommDetail.js')],
      component: () => import('../routes/entcomm/entcommDetail')
    },

我在activeties页跳到detail页，detail页点击某个元素路由跳转到一个新的activeties页（entityId,recordId跟上一个路由不同），这时，用你这个cacahRouter，页面查看元素只看到了两个路由缓存

**Comment by CJY0208** [comment]
明白你的意思了，你是希望同个路由，不同参数也能形成多份不同的缓存

这个功能目前看起来似乎难以实现，因为现在是基于 react-router 做缓存的，但 react-router 本身区分路由时就不包含参数部分，参数部分仅会影响同个路由的表现，并不会衍生出其他的路由，因此无法实现你要的功能

我可以尝试寻找实现方法，但不建议你抱太大希望

**Comment by HuangQiii** [comment]
我也遇到了类似的问题，我的场景是这样的，
```javascript
<CacheSwitch>
     <CacheRoute exact path='/iframe/:name' component={IFRAMEINDEX} />
</CacheSwitch>
```
name是不同名字，都会进到一个iframe warp组件，然后根据name不同获取不同的页面信息

但是这样只会缓存一个路由。

**Comment by CJY0208** [comment]
@ZhiRongYuan @HuangQiii 

重新写了一个库，[react-activation](https://github.com/CJY0208/react-activation)，不依赖 `router` 的纯粹 `<KeepAlive>`  方案

可以解决这个问题，参考[文档](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E5%A4%9A%E4%BB%BD%E7%BC%93%E5%AD%98)和[在线示例](https://codesandbox.io/s/keguanbideyifangwenluyou-tab-shilikeanluyoucanshufenduofenhuancun-ewycx)

## 多份缓存

同一个父节点下，相同位置的 `<KeepAlive>` 默认会使用同一份缓存

例如下述的带参数路由场景，`/item` 路由会按 `id` 来做不同呈现，但只能保留同一份缓存

```javascript
<Route path="/item/:id" render={props => (
  <KeepAlive>
    <Item {...props} />
  </KeepAlive>
)} />
```

类似场景，可以使用 `<KeepAlive>` 的 `id` 属性，来实现按特定条件分成多份缓存

```javascript
<Route path="/item/:id" render={props => (
  <KeepAlive id={props.match.params.id}>
    <Item {...props} />
  </KeepAlive>
)} />
```

**Comment by ZhiRongYuan** [comment]
> @ZhiRongYuan @HuangQiii
> 
> 重新写了一个库，[react-activation](https://github.com/CJY0208/react-activation)，不依赖 `router` 的纯粹 `<KeepAlive>` 方案
> 
> 可以解决这个问题，参考[文档](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E5%A4%9A%E4%BB%BD%E7%BC%93%E5%AD%98)和[在线示例](https://codesandbox.io/s/keguanbideyifangwenluyou-tab-shilikeanluyoucanshufenduofenhuancun-ewycx)
> 
> ## 多份缓存
> 同一个父节点下，相同位置的 `<KeepAlive>` 默认会使用同一份缓存
> 
> 例如下述的带参数路由场景，`/item` 路由会按 `id` 来做不同呈现，但只能保留同一份缓存
> 
> ```js
> <Route path="/item/:id" render={props => (
>   <KeepAlive>
>     <Item {...props} />
>   </KeepAlive>
> )} />
> ```
> 
> 类似场景，可以使用 `<KeepAlive>` 的 `id` 属性，来实现按特定条件分成多份缓存
> 
> ```js
> <Route path="/item/:id" render={props => (
>   <KeepAlive id={props.match.params.id}>
>     <Item {...props} />
>   </KeepAlive>
> )} />
> ```

6666666666666666,有空试一试

**Comment by CJY0208** [comment]
@ZhiRongYuan @HuangQiii 
新发布 v1.8.0 允许按动态路由参数来区分不同缓存，为 `CacheRoute` 增加 `multiple` 属性以启用

参考 https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md#cacheroute-%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E
