### ISSUE TITLE
支持服务端渲染吗？

### ISSUE THREAD

**Issue by xu-lif** [CJY0208/react-router-cache-route#144]
服务端渲染会报错，还是需要特殊的处理呢？
Please update the following components: CacheSwitch
    in CacheSwitch
    in div
    in App
    in Router
    in StaticRouter
    in IntlProvider
    in LanguageProvider
    in Connect(LanguageProvider)
    in Provider
    in Capture
Error: ReactDOMServer does not yet support Suspense.

**Comment by CJY0208** [comment]
OK，用了 freeze，我加个判断再试试

**Comment by CJY0208** [comment]
试试 v1.12.6
