### ISSUE TITLE
CacheRoute pathname prop is gone 

### ISSUE THREAD

**Issue by ruimarques** [CJY0208/react-router-cache-route#148]
Somewhere between version `1.11.0` and `1.12.8`, CacheRoute `pathname` prop is gone. 

This is a breaking change that is not reflected by this lib versioning, meaning it does not seem to follow SEMVER.

**Comment by CJY0208** [comment]
Do you mean that the `pathname` prop of `<CacheComponent>` is changed to `href`? This is an internal component, this change should not cause breaking change. 

What are the problems in your scene?

**Comment by ruimarques** [comment]
I have something like this:

```
<CacheSwitch>
    <CacheRoute path={'some path'} component={SomeComponent} />
</CacheSwitch>
```

```
export default function SomeComponent({ match, pathname }) {
   // pathname undefined 
}
```

Seems `pathname` used to exist in `1.11.0` but no longer in `1.12.8` or earlier.

**Comment by CJY0208** [comment]
I see. This is really an error caused by internal prop changes. I'll fix it

**Comment by CJY0208** [comment]
try 1.12.9

**Comment by ruimarques** [comment]
Thanks, it's fixed !
