### ISSUE TITLE
push和replace时不使用已经缓存的页面

### ISSUE THREAD

**Issue by LWW994214671** [CJY0208/react-router-cache-route#149]
楼主你好，我现在遇到一个问题，就是在A页面已经缓存的时候，从其他页面push或者replace到这个A页面，会直接使用缓存的页面进行显示，页面不会刷新，除了使用didrecover来手动刷新数据是否有其他办法解决？？

**Comment by houchaowei** [comment]
遇到了同样的问题，使用了cache-router 在使用history.push的时候，页面不会自动销毁

**Comment by CJY0208** [comment]
可以在 push 或 replace 前，先[手动卸载](https://github.com/CJY0208/react-router-cache-route#clear-cache)掉对应页面的缓存
