### ISSUE TITLE
中文说明是写错了吗？

### ISSUE THREAD

**Issue by zlmica** [CJY0208/react-router-cache-route#15]
写的 兼容React16.3 以下版本

**Comment by CJY0208** [comment]
因为比较忙所以没进行比较完善的版本测试，能叙述你碰到的问题和提供所使用的 React 版本吗？

**Comment by CJY0208** [comment]
@zlmica 修正了对 React 版本的兼容问题，v1.4.0 版本兼容性调整为 v15+
