### ISSUE TITLE
请问下作者如何处理跳转路径完全相同，但是state不同的情况

### ISSUE THREAD

**Issue by yongchaozeng** [CJY0208/react-router-cache-route#154]
https://codesandbox.io/s/cache-route-demo-forked-yqkzv3?file=/src/App.js
在这个demo地址，我把第49行 search: `?id=${idx}`, 注释掉，然后每次进入页面，虽然都能拿到最新的state，但是Counter组件却缓存了
实际公司项目中，很多传参是通过state，而path地址完全一致，请问有办法解决这个吗

**Comment by yongchaozeng** [comment]
犯蠢了，想了想可以通过path相同，清空前一个来解决

**Comment by CJY0208** [comment]
也可以这样

![image](https://user-images.githubusercontent.com/18415774/188566348-293d3557-5605-4068-824e-4a8ad9e80162.png)
