### ISSUE TITLE
缺少dropByCacheKey, getCachingKeys这两个方法

### ISSUE THREAD

**Issue by peakandyuri** [CJY0208/react-router-cache-route#16]
版本已经更新到1.3.1了，但是没有这两个方法

**Comment by CJY0208** [comment]
你好，可以尝试检查`node_modules/react-router-cache-route/package.json`，确保版本确实升级到了`1.3.1`

**Comment by peakandyuri** [comment]
我是使用npm i xxx@latest进行升级的，package.json里面版本号是1.3.1
{
  "_from": "react-router-cache-route@latest",
  "_id": "react-router-cache-route@1.3.1",
  "_inBundle": false,
  "_integrity": "sha512-IMW/3FYurETpndPyECy5e3lhNlwr3MHsQn05m3Mn/YViP5fHVran/j3oNhFi5N/E8B5ZuLx0Fh0p0xfoTp6M7Q==",
  "_location": "/react-router-cache-route",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "react-router-cache-route@latest",
    "name": "react-router-cache-route",
    "escapedName": "react-router-cache-route",
    "rawSpec": "latest",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/react-router-cache-route/-/react-router-cache-route-1.3.1.tgz",
  "_shasum": "fa8c79b62e94ae37d0fa93eaed871752833c5ff1",
  "_spec": "react-router-cache-route@latest",
  "_where": "E:\\learn\\reacts\\wx-mobile-example",
  "author": {
    "name": "CJY0208"
  },
  "bugs": {
    "url": "https://github.com/CJY0208/react-router-cache-route/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "cache-route for react-router base on react v15+ and router v4+",
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "rollup": "^0.61.2",
    "rollup-plugin-babel": "^3.0.5",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-uglify": "^4.0.0"
  },
  "homepage": "https://github.com/CJY0208/react-router-cache-route",
  "keywords": [
    "keep-alive",
    "react",
    "react-router",
    "cache"
  ],
  "license": "ISC",
  "main": "index.js",
  "name": "react-router-cache-route",
  "peerDependencies": {
    "prop-types": ">=15",
    "react": ">=15",
    "react-router-dom": ">=4"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/CJY0208/react-router-cache-route.git"
  },
  "scripts": {
    "build": "rollup --config"
  },
  "version": "1.3.1"
}

**Comment by CJY0208** [comment]
有没有尝试过移除依赖并重新安装？我能确保的是 `1.3.1` 确实是有那两个方法的
