### ISSUE TITLE
CacheSwitch报错

### ISSUE THREAD

**Issue by webgldawn** [CJY0208/react-router-cache-route#19]
react-router-cache-route V1.3.1，react V15.2.1，react-router [V4.3.1，CacheSwitch报错如下：
Uncaught Error: CacheSwitch.render(): A valid React element( or null ) must be returned. You may returned undefined, an array or some other invalid object.

**Comment by CJY0208** [comment]
OK，问题已记录，近期将尝试修复

之前 README 说明为支持 v16.3- 版本，经测试后 v15 存在不兼容情况，暂时修正了兼容性的说明，调整为 v16+

**Comment by webgldawn** [comment]
谢谢CJY0208！下午做了React升级到V16+的尝试，发现问题很多，现在还没有解决完毕，弱弱的问下，react-router-cache-route有在近期支持React V15.*的计划吗？

**Comment by CJY0208** [comment]
@webgldawn 有的，不过目前仅发现了这一个问题，还不清楚是否存在其他 v15+ 上的兼容性问题，可能会需要一些时间

v16 发布已经很长时间了，上面的新特性很值得对 React 版本做升级噢

**Comment by CJY0208** [comment]
@webgldawn 修正了对 React 版本的兼容问题，v1.4.0 版本兼容性调整为 v15+
