### ISSUE TITLE
Error after upgrade react-router@4.4.0

### ISSUE THREAD

**Issue by HughHzWu** [CJY0208/react-router-cache-route#24]
![image](https://user-images.githubusercontent.com/11567604/54519110-b7dfc000-49a0-11e9-9b77-316a1c7da124.png)

react-router@4.4.0 中Router 的 context 使用了‘create-react-context’的方式，旧的方式不再支持

**Comment by David-Gan** [comment]
我也遇到同样问题。。。

**Comment by CJY0208** [comment]
OK，近期尝试修复

**Comment by CJY0208** [comment]
@HughHzWu @David-Gan 

Hello，v1.4.2 使用 `withRouter` 处理 `CacheSwitch` 修复了 react-router 4.4+ 兼容问题

感谢 @xuandiboss

**Comment by David-Gan** [comment]
感谢！ @CJY0208

**Comment by HughHzWu** [comment]
> @HughHzWu @David-Gan
> 
> Hello，v1.4.2 使用 `withRouter` 处理 `CacheSwitch` 修复了 react-router 4.4+ 兼容问题
> 
> 感谢 @xuandiboss

感谢！
