### ISSUE TITLE
react 16.3+版本

### ISSUE THREAD

**Issue by tiantian000** [CJY0208/react-router-cache-route#26]
请问react 16.3+ 有兼容方案吗？

**Comment by CJY0208** [comment]
理论上是支持的，目前是在某个版本上遇到了问题吗？

**Comment by tiantian000** [comment]
react升级到16.4.2后，缓存失效了，这个插件最高支持到那个版本呢？

**Comment by CJY0208** [comment]
抱歉，一直没有时间来查找问题

我这边尝试了，目前最新版 v1.4.3 是可以支持到 `react` 16.8.6 + `react-router-dom` 5.0.0，所以应该不是插件的问题，请问你目前还遇到问题吗？

另外使用的 `react-router-dom` 和 `react-router-cache-route` 的版本都是多少呢？

**Comment by CJY0208** [comment]
目前对各版本做了较全面的兼容，尝试最新版本后看是否解决问题
