### ISSUE TITLE
共用滚动容器（document.body）时未能保存不同视图的滚动位置

### ISSUE THREAD

**Issue by huanzheke** [CJY0208/react-router-cache-route#27]
情景是在cache的商品列表页滚动一定距离然后点击去商品详情页,再返回来滚动距离没了.

**Comment by huanzheke** [comment]
版本为1.3.1, 项目是h5页面.

**Comment by CJY0208** [comment]
能否尝试检查除了滚动距离外，其他的列表数据是否被缓存了？

需要先排除“列表页与详情页共用了 body 作为滚动容器导致滚动位置被重置”的问题

**Comment by huanzheke** [comment]
> 能否尝试检查除了滚动距离外，其他的列表数据是否被缓存了？
> 
> 例如已经请求的列表数据，或者检查列表页组件生命周期是否从头开始了
> 
> 先需要排除`列表页与详情页共用了 body 作为滚动容器导致滚动位置被重置`的问题

列表页确实跟详情页共用了body滚动容器,但是没办法的事情呀,我们的列表要求吸顶还有置顶按钮,用window来操作

**Comment by huanzheke** [comment]
仔细观察到,商品详情第一次返回到列表的话是可以cache滚动条的,之后又不行了,这是啥子原因,ios很烦

**Comment by CJY0208** [comment]
你们的需求应该也可以通过自建滚动容器来实现

目前来说 `CacheRoute` 无法处理共用滚动容器的情况，目前在和 [react-keep-alive](https://github.com/StructureBuilder/react-keep-alive/issues/4) 作者讨论 `saveScrollTop` 函数功能，如果得以支持可以考虑一下这个方案

后续 `CacheRoute` 也会尝试支持此方案，不过时间待定，目前比较忙

`saveScrollTop` 行为的运作方式大致为：

在组件被缓存时将所有订阅了 `saveScrollTop` 需求的滚动容器 scrollTop 记住，并于组件恢复时恢复各订阅容器的 scrollTop，这个功能理论上将可作用于共用滚动容器的情况

**Comment by huanzheke** [comment]
> CacheRoute



> 你们的需求应该也可以通过自建滚动容器来实现
> 
> 来说目前`CacheRoute`无法处理共用滚动容器的情况，目前在和[反应，保活](https://github.com/StructureBuilder/react-keep-alive/issues/4)作者讨论`saveScrollTop`函数功能，如果得以支持可以考虑一下这个方案
> 
> 后续`CacheRoute`也会尝试请立即获取iTunes此方案，不过时间待定，目前比较忙
> 
> `saveScrollTop` 行为的运作方式大致为：
> 
> 在组件被缓存时将所有订阅了`saveScrollTop`需求的滚动容器scrollTop记住，并于组件恢复时恢复各订阅容器的scrollTop，这个功能理论上将可作用于共用滚动容器的情况

现在已经解决了,用div滚动,但问题是每个页面都这样的话导致很重复

**Comment by Sam618** [comment]
@huanzheke 可以尝试在离开列表页时，保存滚动值；返回到列表页时触发生命周期，然后在激活这个生命周期中重新设置滚动值。

**Comment by huanzheke** [comment]
> @huanzheke 可以尝试在离开列表页时，保存滚动值；返回到列表页时触发生命周期，然后在激活这个生命周期中重新设置滚动值。

谢谢大佬,不怎么好单独维护,还是用一个容器让他自生自灭吧.

**Comment by CJY0208** [comment]
@huanzheke 

新发布 `v1.8.0` 尝试解决共用容器问题，为 `CacheRoute` 增加 `saveScrollPosition` 属性可实现此功能
