### ISSUE TITLE
ie10和ie9下报错，导致页面无法渲染

### ISSUE THREAD

**Issue by huiBuiling** [CJY0208/react-router-cache-route#28]
![image](https://user-images.githubusercontent.com/20200628/56008907-72e54a00-5d10-11e9-9866-a2b652194de8.png)

You should not use <Switch> outside a <Router>

**Comment by huiBuiling** [comment]
使用Switch正常，使用CacheSwitch就会报错，例子也是按demo写的

**Comment by CJY0208** [comment]
其他浏览器如 `chrome` 功能正常吗？能否提供可复现的最小 `demo` 片段呢

**Comment by huiBuiling** [comment]
Edge和chrome都正常的
![image](https://user-images.githubusercontent.com/20200628/56011570-c2c90e80-5d1a-11e9-9ffd-969bb73d1678.png)

**Comment by CJY0208** [comment]
OK，感谢反馈！近期会尝试解决

**Comment by huiBuiling** [comment]
好的，非常感谢

**Comment by CJY0208** [comment]
Hello，看来看去有些奇怪

`<CacheSwitch>` 的工作方式为继承 `<Switch>` 并重写了 `render` 方法，上述报错是出现在 `<Switch>` 的原有 `render` 方法中

按理来说，重写 `render` 方法后，使用 `<CacheSwitch>` 时无论如何都不应该出现上述报错才对

我猜测可能是某种未知的兼容性问题，但缺乏更多有效的信息，能否提供完整的 `Demo` 目录呢？

可以加我 QQ：375564567 以压缩包形式提供，或者在此处张贴全部 `Demo` 代码

另外需要知晓 `Demo` 中的 `react`、`react-dom`、`react-router` 版本号，十分感谢！

**Comment by zxfgll** [comment]
我也遇到这个问题，除了ie9和ie10有这个问题，其他现代浏览器都没有这个问题

**Comment by zxfgll** [comment]
测试后"react-router-cache-route": "^1.4.1" 没问题，"react-router-cache-route": "^1.4.2"存在这个问题

**Comment by huiBuiling** [comment]
![image](https://user-images.githubusercontent.com/20200628/56479150-34a51300-64e6-11e9-86d5-3d5e2b8e7e3a.png)

"react": "^16.0.0",
"react-dom": "^16.0.0",
"react-router": "^4.1.1",
"react-router-cache-route": "^1.3.1",

edge下是可以的，之前也一直用的可以的，是后面突然不行的

**Comment by huiBuiling** [comment]
@zxfgll 那我也测试下

**Comment by huiBuiling** [comment]
@CJY0208 大大，这边删包重新install可以了，不确定是不是是版本，但是之前确实用了半年很赞，也没有报错哦

**Comment by CJY0208** [comment]
@huiBuiling @zxfgll 

可能是 `react-router` 的 `withRouter` 在 ie9 / ie10 下有什么暗病，如果目前降版本能用的话，就先用着啦，最近忙业务一直没时间看

因为 `1.4.2` 是为了兼容 `react-router` v4.4+ 的修复版本，如果项目中 `react-router` 版本没有达到 4.4 的话，是不需要升级到 `1.4.2` 的

这条 issues 先保持开启吧，后续尝试能否无感知修复掉，正好也做个解法标记，谢谢你们啦

**Comment by huiBuiling** [comment]
好的

**Comment by CJY0208** [comment]
@huiBuiling @zxfgll 
v1.4.3 尝试识别 `router-router` v4.4+ 特征来决定是否使用 `withRouter` 包裹 `CacheSwitch` 组件，在版本低于 4.4 时不会使用 `withRouter`

可以试试看，是否修复了当前 Issues
