### ISSUE TITLE
react 16.8.6 下报错

### ISSUE THREAD

**Issue by ihaichao** [CJY0208/react-router-cache-route#29]
![WechatIMG117](https://view.didistatic.com/static/dcms/478dr1lwxxjvqb4gem_1224x640_compress.jpeg)

#### 错误版本
react: 16.8.6
react-router-cache-route: 1.4.1

#### 正常版本
react: 16.6.0
react-router-cache-route: 1.4.1

**Comment by CJY0208** [comment]
请尝试升级 `react-router-cache-route` 到 1.4.3 版本

**Comment by ihaichao** [comment]
@CJY0208 升级之后仍然有同样的报错

**Comment by CJY0208** [comment]
react-router-dom 是啥版本的？？

**Comment by ihaichao** [comment]
4.3.1

**Comment by CJY0208** [comment]
大概猜到了原因了，一会儿尝试修复

**Comment by CJY0208** [comment]
尝试 v1.4.4

**Comment by ihaichao** [comment]
好的，我有空尝试下，想问下这个库考虑加入单元测试吗，不然在生产环境中使用还是有风险的

**Comment by CJY0208** [comment]
是应该加上测试，但目前时间和能力有限，还没办法实施
