### ISSUE TITLE
引入antd-pro的脚手架里无效？

### ISSUE THREAD

**Issue by heartrainy** [CJY0208/react-router-cache-route#3]
你好，我发现这个用在阿里那个antd-pro的脚手架里还是不起作用，看了下代码 可能是跟dva框架的按需加载有关，是不是用了这个就不能使用按需加载了？

**Comment by CJY0208** [comment]
是类似于 [`react-loadable` ](https://github.com/jamiebuilds/react-loadable) 的按需加载吗？

我在自己项目中做了简单的实现，配合 `CacheRoute` 是能正常工作的，能否提供重现的 demo 呢

**Comment by CJY0208** [comment]
看了 dva 使用的 react-router 是 v3 版本，目前这个工具暂时只支持 v4 哦，也就是 react-router-dom 的版本

实际上似乎 v3 问题也不大，这几天我找时间看看能否修改要求的 react-router 版本

**Comment by heartrainy** [comment]
用的项目是antd-pro，里面的dva框架用的router应该是v4版本，这个是pro的项目地址https://github.com/ant-design/ant-design-pro/
在src下的common文件的里面有个路由配置router.js 里面有个dynamicWrapper方法 好像createElement了，是不是这个原因导致的缓存没保存？

**Comment by heartrainy** [comment]
原先的思路是antd的tab组件和路由分开来写，好像实现不了，现在把路由写在tab的content里再配合你的缓存Route就可以了
