### ISSUE TITLE
浏览器前进按钮跳转页面，不会缓存前一个页面

### ISSUE THREAD

**Issue by qiuziz** [CJY0208/react-router-cache-route#33]
使用默认缓存设置forward 正常push back是ok的

但是如果点击浏览器的前进按钮，是没有被缓存的

点击浏览器前进后退按钮 history中的action都是POP，所以会取消缓存，这个可以支持下吗

**Comment by CJY0208** [comment]
可能有一定难度，因为 cache-route 依附于 react-router 实现，但目前遇到的是 react-router 也没有做到的问题，如果需要支持的话，可能会是一些 hack 或者有味道的代码

也有一个方法：将 when 设置为 always ，业务代码中在跳转后识别跳转前路由，判断两者的前后关系，再借助 dropCache 方法取消缓存，应该可以实现此功能

**Comment by qiuziz** [comment]
确实, 我在路由配置中添加路由顺序处理吧

另外，behavior这个能暴露多点参数吗 比如是cache还是recover，

在写入场动画和出场动画，发现加了入场动画（translateX(100%) => translateX(0)）后，back也是会触发这个，每个页面在didRecover移除这个太麻烦了

或者你有什么其他处理方式吗

**Comment by CJY0208** [comment]
这个期望的目的是更好地控制转场动画吗？我在想如何让 cache-route 直接支持转场动画的设计，如果暴露 isCached 或者 isRevover 似乎还不够灵活

**Comment by qiuziz** [comment]
是的，但目前看来，cache-route 入场动画无法完美实现，我无法获知当前页面是否后退而取消入场动画。

如果按照ReactCSSTransitionGroup 来进行className的动态变换就完美了

是否考虑下先暴露出isCached/isRevover 来过渡下呢

**Comment by CJY0208** [comment]
我期望能直接走到支持 TransitionGroup 这一步上，但目前没时间做...需要到 6 月份了

**Comment by qiuziz** [comment]
那先hack下吧 项目现在中需要用到

感谢

**Comment by ellisonLou** [comment]
> 那先hack下吧 项目现在中需要用到
> 
> 感谢
请问你是怎么hack的呢？我们项目里面用到了多个tab缓存页面，在用reduxRouter.push 或者 浏览器的前进后退都会丢失缓存。感谢！

**Comment by qiuziz** [comment]
@ellisonLou 不是太明白你说的 如果 是点击浏览器前进后退无法缓存的话，上面@CJY0208 有提供方案

> 也有方法：将 `when` 设置为 `always` ，业务代码中记录跳转前后的路由路径，提供方法判断两者的前后关系，再借助 `dropCache` 方法手动取消缓存，理论上可以实现此功能

如果是做路由控制的话，需要自己hack `behavior` 提供的参数 来回切换显示和隐藏 通过变量累加来判断是前进还是后退 但这种方案不太理想 还是有少数情况下出现错误动画
