### ISSUE TITLE
使用的问题

### ISSUE THREAD

**Issue by micalotime** [CJY0208/react-router-cache-route#35]

**Comment by micalotime** [comment]
是用插件的时候
不正常：
<CacheRoute exact path="/list" component={List} when="always" /> 
    <Switch>
      <Route exact path="/item/:id" component={Item} />
    </Switch>

正常：
<CacheRoute exact path="/list" component={List} when="always" /> 
    <Switch>
      <Route exact path="/item/:id" component={Item} />
      <Route exact path="/list" />
    </Switch>

**Comment by CJY0208** [comment]
额...我没看懂你的意思，是配合 Switch 时的问题吗？

**Comment by micalotime** [comment]
因为我这里如果没有匹配到路径，就会返回到404的界面，如果不在switch中加上一个对应的路由，会出现对应的界面和404界面在同一页中 @CJY0208 ，而且使用方法里，<Router>里面只能有一个节点，不然会报错，需要一个<div>包裹着，不知道你们有没有这个问题

**Comment by CJY0208** [comment]
是和 `react-router` 本身的 `Switch` 配合使用吗？可以用 `CacheSwitch` 替代 `Switch` 试试

https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

`注意：缓存语句不要写在 Switch 组件当中，因为 Switch 组件会卸载掉所有非匹配状态下的路由，需使用 CacheSwitch 替代 Switch`
