### ISSUE TITLE
能让我的子组件不参与缓存吗

### ISSUE THREAD

**Issue by johanazhu** [CJY0208/react-router-cache-route#36]
我的H5其中一页，我用react-router-cache-route 缓存了，但是我希望其中的一个子组件不参与缓存，这个子组件与父组件的联系是一个点击事件， 能做到吗

**Comment by CJY0208** [comment]
可以使用缓存生命周期函数配合父组件的状态管理来实现子组件不缓存

https://github.com/CJY0208/react-router-cache-route#lifecycles

**Comment by johanazhu** [comment]
我想不通，为什么一缓存，我的子组件中的事情变成了null，求解答

**Comment by CJY0208** [comment]
子组件的什么？需要更详细的表述

**Comment by johanazhu** [comment]
子组件是头部的导航条，这这边是嵌在app中的移动端H5，app中点击 "订单"（跳地址）进入H5订单列表，点击导航条中的返回按钮，关闭webview。但是如果我从订单列表再往里面点一层（比如进入订单详情时），从订单详情中返回，back事情为null

**Comment by CJY0208** [comment]
能否提供一个简单的 demo 呢？需要了解你是如何给导航条提供 back 事件的，以及在页面跳转过程中的一些细节

应该和 CacheRoute 无关，CacheRoute 仅仅是将组件隐藏，不会干涉组件的状态

**Comment by johanazhu** [comment]
感谢你的回答，刚刚我一直在试你说的“使用缓存生命周期函数配合父组件的状态管理来实现子组件不缓存”，我想是因为我的导航条是公用的，如果从app进入订单列表，导航条生命周期注册了goBack（针对安卓手机，有物理返回键），当用户点击物理返回键的时候，会调用H5中的goBack事件。

当我从订单列表进入订单详情时，我的导航条相当于又注册了goBack，顶替了订单列表中的goBack，所以我怎么按物理返回键都没有用，所以如果在缓存中，不缓存子组件，那么事情就解决了，让订单详情进入订单列表的时候，导航条再一次注册，顶替了订单详情中的goBack

再次感谢回复

**Comment by CJY0208** [comment]
看了你的答复，猜测你将导航栏放在了 Route 视图中，变成了 List 和 Item 组件的一部分

像这样的情况，其实导航栏是不需要随着路由变化的，跟随路由变化的区域应该是导航栏之下的那部分，也许你可以尝试如下的路由配置结构

```javascript
import React from 'react'
import {} from 'react-router-dom
import { CacheRoute, CacheSwitch } from 'react-router-cache-route'

import NavBar from '../NavBar'
import List from '../List'
import Item from '../Item'

const RouterConfig = () => (
  <Router>
    <NavBar /> {/* 导航栏不需要放在 Route 视图中 */}
    <CacheSwitch>
      <CacheRoute exact path="/list" component={List} />
      <Route exact path="/item/:itemId" component={Item} />
    </CacheSwitch>
  </Router>
)

export default RouterConfig
```

**Comment by johanazhu** [comment]
对的，因为我的项目和app的头之间有千丝万缕的关系，所以导航是放在route中的 ^_^
