### ISSUE TITLE
希望能在何时缓存时自定义化

### ISSUE THREAD

**Issue by johanazhu** [CJY0208/react-router-cache-route#38]
选择缓存功能的when只能选“always”，“forward”，“back”，forward是通过history.action是否是‘pop’来判断，也就是说如果我用react-router中的goBack()才会让页面缓存
我希望能自定义化，在我调用指定history.push() 时让他缓存住

**Comment by CJY0208** [comment]
有打算允许 when 作为 function 使用，使用 nextProps 作为参数，返回 true/false 来决定是否在下个组件状态进行缓存，这样子如何呀？

**Comment by johanazhu** [comment]
好啊，我没问题

**Comment by CJY0208** [comment]
@johanazhu v1.5.0 中已经允许 when 传递函数

https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md#when-%E5%8F%96%E5%80%BC%E8%AF%B4%E6%98%8E
