### ISSUE TITLE
能否支持一下 自定义 传 history 对象 

### ISSUE THREAD

**Issue by Kage336** [CJY0208/react-router-cache-route#39]
新版的 react-router-dom 好像没法传 自定义 的 history 对象，有些项目需要集中的路由管控，然后和 react-router-dom 不是同一个 history 对象，导致所有的  action 总是 POP ，希望能支持一下

**Comment by CJY0208** [comment]
不是很理解你的意思...传递自定义 history 对象指的是类似于一下的用法吗？

```javascript
import { Router } from "react-router";
import { createBrowserHistory } from "history";

const history = createBrowserHistory()

<Router history={history}>
  <App/>
</Router>
```

**Comment by Kage336** [comment]
对，但是react-router-dom 现在不能自定义传递history 对象，我自己维护了一份，但是你取的是props 上面的 history

**Comment by CJY0208** [comment]
我看了最新的[官方文档](https://reacttraining.com/react-router/web/api/Router)和 [Router 源码](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L58)，似乎还是可以传递自定义 history 的

因为 CacheRoute 的表现是基于 Route 的，所以也会取 react-router 所用的 history，也就是 Router 的上下文 history

能否提供代码样例？

**Comment by Kage336** [comment]
react-router 可以传，但是 react-router-dom的 hashRouer不可以，算了，我从ref上取到react自己的history对象了，还有个问题，写转场动画是在behavior 上面加样式吗？

**Comment by CJY0208** [comment]
HashRouter 会自动生成 history，可替换为如下

```javascript

const history = createHashHistory()

<Router history={history}>
  ...
</Router>
```

目前还不支持转场动画功能，可以关注 #30
