### ISSUE TITLE
关于className的完全控制

### ISSUE THREAD

**Issue by javaLuo** [CJY0208/react-router-cache-route#4]
hi，这是一个非常棒的东西。

但我想说说我遇到的情况：
现在的处理方式是添加包裹组件，设置display:none来实现的keep-alive
但display:none会导致内部的一些子组件丢失高度，某些子组件的滚动条就会重置到顶部

目前组件有个className可以设置。
我更希望组件不要去设置display:none，而是我能自己定义className, 来完全控制怎么隐藏。
组件能帮我在componentDidCache时添加这个className, 在componentDidRecover时去掉这个className
就太棒了

比如我现在的需求，我需要这么隐藏：
```
className {
 position: absolute;
 top:0;
 left:0;
 visibility: hidden;
 z-index: -1;
}
```

以上是我的一个建议... 望考虑

**Comment by CJY0208** [comment]
可以的，近期会研究如何加入，这是个不错的主意，谢谢啦

**Comment by CJY0208** [comment]
@javaLuo 
v1.2.0 中新增了 `behavior` 属性来完全自定义隐藏方式，使用方式如下
```javascript
...
<CacheRoute
  ...
  behavior={cached =>
    cached
      ? {
          style: {
            position: 'absolute',
            zIndex: -9999,
            opacity: 0,
            visibility: 'hidden',
            pointerEvents: 'none'
          },
          className: '__CacheRoute__wrapper__cached'
        }
      : {
          className: '__CacheRoute__wrapper__uncached'
        }
  }
/>
...
```

另外，默认的隐藏行为由 `display: none;` 修改为

```javascript
{
  position: 'absolute',
  zIndex: -9999,
  opacity: 0,
  visibility: 'hidden',
  pointerEvents: 'none'
}
```
试试目前是否能解决你的问题？

**Comment by javaLuo** [comment]
搞定！
非常感谢

**Comment by wSLecHayfIeNdock** [comment]
Hello! @CJY0208 有空处理下 `className` 空值 😂

**Comment by CJY0208** [comment]
> Hello! @CJY0208 有空处理下 `className` 空值 😂

@wSLecHayfIeNdock  是未传递 className 时造成的 class="undefined" 现象吗？

**Comment by wSLecHayfIeNdock** [comment]
@CJY0208 默认隐藏还是需要用 `display: none` 合适些

上面的问题，提供 `className` 额外处理就好了吧

[demo](https://codesandbox.io/s/vmmr6wx565) 在 PC 端上，就有问题

**Comment by CJY0208** [comment]
@wSLecHayfIeNdock 确实如此，如果以 `document.body` 作为滚动对象的话，似乎难以避免 `display: none` 时 scrollTop 被重置的问题，不过因为修改了默认隐藏方案而影响到其他视图确实不是一个很好的体验

我一会儿就恢复为 `display: none`  默认方案，需要 @javaLuo 同学知晓，如果你使用了默认方案的话，更新后的版本可能导致你的问题重现，需要手动使用 `behavior` 属性修复
