### ISSUE TITLE
cacheLifecycles 能否支持多个订阅？

### ISSUE THREAD

**Issue by Kage336** [CJY0208/react-router-cache-route#40]
同一个 routes 分支下的 cacheLifecycles 现在只支持订阅一次，多次订阅会覆盖之前的订阅，希望支持多次订阅

**Comment by CJY0208** [comment]
啊...我居然没回复这条...一直以为已经回复了，事实上这条 issues 刚发了 5 分钟就看到了...

要增加多次订阅是可以实现的，但这样会造成 breaking change，更改了过往的约定，可能会对已在使用中的同学们造成影响，所以此处暂时保守处理，不改变现有功能

可以在单次订阅内使用其他技术拓展为多次订阅，例如 EventBus
