### ISSUE TITLE
react-router-cache-route在umi框架里怎么使用啊

### ISSUE THREAD

**Issue by hzcdt** [CJY0208/react-router-cache-route#41]
在之前dva-cli脚手架生成的框架里，有一个可以由我们自定义配置的router.js，所以我们可以import react-router-cache-route去配置缓存路由，但是在umi里不管是约定式路由还是配置的路由，其最终生成有效的路由文件的过程都是框架自己做的，我该在哪一步去引入 react-router-cache-route配置缓存路由呢？

**Comment by CJY0208** [comment]
我需要研究一下，还没用过 umi

**Comment by CJY0208** [comment]
看了一下文档，似乎确实是没有下手之处，目前需要等待 umi 的兼容

@xiaohuoni umi 的同学已经在尝试增加 CacheRoute 了

进度在 https://github.com/umijs/umi/pull/3084 中，可以关注此处

**Comment by CJY0208** [comment]
feature issues 为 https://github.com/umijs/umi/issues/3091

**Comment by hzcdt** [comment]
@CJY0208 这效率杠杠的，希望umi能兼容一套路由缓存的方案
