### ISSUE TITLE
希望能添加配置来设置最大缓存数量

### ISSUE THREAD

**Issue by vimcaw** [CJY0208/react-router-cache-route#42]
有时候页面栈长度太大会导致缓存的页面越来越多，可能会引起性能问题，希望添加属性来配置最大缓存数量，超出数量时，移除最早被缓存的页面（页面栈底部）。

我尝试用`getCachingKeys()`来获取缓存的页面，然后用`dropByCacheKey()`来清除，但是发现`getCachingKeys()`获取的列表并不是按照时间顺序来排列的，所以还是希望库本身能支持这个功能。

**Comment by CJY0208** [comment]
自动删除某些缓存可能不会是一个可预期的行为

我可以尝试增加 getCachingNodes 方法，返回缓存中的组件实例

实例上增加 createTime 和 updateTime 属性，分别表示缓存节点的创建时间和缓存状态变化时间

这样可以由使用者自己来主动拓展出上述功能，也不会影响 cache-route 本身

如何呀？

**Comment by vimcaw** [comment]
可以，非常感谢！只要能识别时间先后的顺序就行。

**Comment by CJY0208** [comment]
ok，一会儿我试试，好了通知

**Comment by CJY0208** [comment]
@vimcaw v1.7.0 上增加了 getCachingComponents 功能，将返回一个 cachingComponentMap 对象结构，以 cacheKey 为键，以 CacheComponent 实例为值

值上将附带 __cacheCreateTime 及 __cacheUpdateTime 属性，分别表示缓存节点的创建时间和缓存状态变化时间

看看是否能满足功能，暂不写进 README 中

**Comment by vimcaw** [comment]
@CJY0208 更新了看了下，确实有了，感谢！另外如果方便的话可以提供个回调函数吗，在缓存一个新页面后调用回调，这样会更方便。

**Comment by CJY0208** [comment]
这个功能跟着 react-router 本身的 history 走就行了，用 history.listen 增加监听

cache-route 缓存状态的变化必然是因为 router 发生变化引起的

**Comment by vimcaw** [comment]
OK，完美解决，非常感谢！

**Comment by CJY0208** [comment]
看起来似乎尝试清除的缓存节点是刚被新建的那个？例如正要去往 /user-center 而尝试清空 /user-center

**Comment by vimcaw** [comment]
缓存更新时间貌似有点奇怪。

浏览路径还是：`/message` > `/user-center` > `/services`

控制台时间格式化输出：

![image](https://user-images.githubusercontent.com/21964227/64681463-5b261380-d4b2-11e9-82a7-c865444fd703.png)
