### ISSUE TITLE
删除react弃用的生命周期方法已消除警告？

### ISSUE THREAD

**Issue by ppbl** [CJY0208/react-router-cache-route#43]
现在有一些生命周期钩子函数已经提示弃用了，可否清理一下~😁

**Comment by CJY0208** [comment]
Hello，我编辑了一个[在线示例](https://codesandbox.io/s/cacheroute-online-demo-t8f8e)，没有复现错误提示，使用的工具如下

- 构建：create-react-app
- react v16.9.0
- react-dom v16.9.0
- react-router-dom v.5.1.0
- react-router-cache-route v1.7.0

**Comment by ppbl** [comment]
好吧我又仔细看了下是因为用了 dva，引用的 react-router 4.3 导致的
![image](https://user-images.githubusercontent.com/33046279/65608290-90695000-dfe0-11e9-9fc9-469cc075564f.png)
但是控制台提示 `CacheSwitch` 只有 我们这个库才有，
然后我在 `CacheComponent` 发现了这个， `getDerivedStateFromProps `，因为这个貌似以后也不太建议使用所以我以为是这个导致的。。😂
非常感谢👍👍 辛苦了（下次我一定再认真找找源头。。。）
如果有什么我可以帮忙的，我有时间的话可以提一下 pr👀

**Comment by CJY0208** [comment]
CacheSwitch 为了不影响 Switch 原有的逻辑，是直接继承的 Switch，然后... 4.3 里的 Switch 确实存在 `componentWillMount` 周期，所以报了 warning

https://github.com/ReactTraining/react-router/blob/v4.3.0/packages/react-router/modules/Switch.js#L22

这里顺便给自己另一个库 [react-activation](https://github.com/CJY0208/react-activation) 打广告，嘻嘻

同样是 `<KeepAlive>` 功能，但这次是纯粹的、不依赖 `router` 的实现

[Online Demo](https://codesandbox.io/s/affectionate-beaver-solkt)

<img src="/CJY0208/react-activation/raw/master/docs/basicReactActivation.gif">

感兴趣可以试试
