### ISSUE TITLE
列表页和详情页公用位置

### ISSUE THREAD

**Issue by hzfvictory** [CJY0208/react-router-cache-route#44]
列表页A
详情页B
加入A跳转到B,A之前滚动多少距离到B页面scrollTop就是多少，然后B滚动后，再用push方法跳转到A,A页面现在的位置就是B页面的位置，B页面用goback()方法跳转的时候没有此问题出现。

要求 A 跳转 B  直接问到B的顶部，B会A页面，A还是之前的高度

**Comment by hzfvictory** [comment]
版本有提到 unmount 和 saveScrollPosition  什么时候支持

**Comment by hzfvictory** [comment]
我现在 准备用  componentDidCache来获取scrollTop的高度，然后在用componentDidRecover赋值，但是遇到了一个问题，没有办法获取scrollTop的高度，每次都是0: 代码

```
 constructor(props: any) {
        super(props);
        this.state = {
            data: [],
            total: 0,
            current: 1,
            loading: true,
            scrollTop: 0
        };

        props.cacheLifecycles.didCache(this.componentDidCache);
        props.cacheLifecycles.didRecover(this.componentDidRecover);
    }

    componentDidCache = () => {
        console.log(ReactDOM.findDOMNode(document.documentElement).scrollTop, 'go');
        this.setState({
            scrollTop: document.documentElement.scrollTop
        });
    };

    componentDidRecover = () => {
        const {scrollTop} = this.state;

        console.log(scrollTop, 'back');
        window.scroll(0, scrollTop);
    };


```

**Comment by CJY0208** [comment]
与 #27 相同

didCache 触发时可能已经错过了保存高度的时机，或者滚动容器是 document.body？
之后会尝试重新调整生命周期的触发顺序，在那之前也许需要如 #27 所说，通过自建滚动容器解决

**Comment by hzfvictory** [comment]
我新建局部滚动的容器 content ,还是获取不到想要高度 依然是0。  document.body也试过也不行
```
componentDidCache = () => {
        console.log(ReactDOM.findDOMNode(document.getElementById('content')).scrollTop, 'go');
    };
```

**Comment by hzfvictory** [comment]
看你的源码  cacheLifecycles是在componentDidUpdate,
```
componentDidUpdate(prevProps, prevState) {    
  if (prevState.matched === true && this.state.matched === false) {
      if (this.props.unmount) {
        const parentNode = get(this.wrapper, 'parentNode')
        this.__parentNode = parentNode

        run(
          this.__parentNode,
          'insertBefore',
          this.__placeholderNode,
          this.wrapper
        )
        run(this.__parentNode, 'removeChild', this.wrapper)
      }
      this.__cacheUpdateTime = Date.now()
      return run(this, 'cacheLifecycles.__listener.didCache')
    }
  }
```
我在componentDidUpdat生命周期打印滚动的高度，触发一次render能获取到scrollTop,但是didCache依然是没有高度
![image](https://user-images.githubusercontent.com/38562125/65476844-cd392800-deb6-11e9-8013-6fdf87b91f1a.png)


话外  ：这个didCache获取不到dom节点的各种高度，还能做些什么。。。。
通过自建滚动容器，是指的每个滚动的盒子都是单独的？？？那我维护性太差了

**Comment by CJY0208** [comment]
嗯嗯，didCache 的触发时机是晚了一些，触发的时候也许 dom 节点滚动位置已经发生了改变，所以获取不到滚动位置

这个之前没有考虑到，上边说到了会尝试提前到 didUpdate 之前去做

例如利用 shouldComponentUpdate 周期，加入 willCache 钩子，应该可以解决问题

didCache 设计的目的是实现类似 didMount 或者 willUnmount 的生命周期钩子，可以用来做类似于 clearTimeout 或者 clearInterval 之类的行为，不过没有很详细考虑触发时机的问题

另外，最近还提供了纯粹的、不依赖路由的 KeepAlive 功能，有兴趣可以试试

https://github.com/CJY0208/react-activation/blob/master/README_CN.md

**Comment by hzfvictory** [comment]
这个个人觉得不还错，解决了滚动的问题，文档写的也挺详细的。主要是现在的项目已经很完善了，用那个得话侵入性比较强，不适合现有的项目。膜拜大佬，很贴心 给我转发的测试中文文档。

我用别的方式先解决我那个问题吧，你有时间更新了通知下我 谢谢

**Comment by CJY0208** [comment]
@hzfvictory 
新发布 v1.8.0 尝试解决共用容器问题，为 `CacheRoute` 增加 `saveScrollPosition` 属性可实现此功能
