### ISSUE TITLE
不兼容react-router-dom v5.0+ 版本

### ISSUE THREAD

**Issue by eltonchan** [CJY0208/react-router-cache-route#45]
升级到react-router-dom 发现无法工作了

**Comment by CJY0208** [comment]
cache-route 的版本是多少呢？

**Comment by eltonchan** [comment]
> cache-route 的版本是多少呢？

我刚升级到最新的1.7.0 还是不行

**Comment by CJY0208** [comment]
有没有报错？我看看能否重现

**Comment by eltonchan** [comment]
> 有没有报错？我看看能否重现

没有报错，就是子组件重新render了，没有keep住。嗯 我先去我搭一个复现的demo

**Comment by eltonchan** [comment]
方便加下微信或者qq嘛、我可以发给你微信

**Comment by CJY0208** [comment]
375564567

**Comment by eltonchan** [comment]
嗯嗯 加了 ~

**Comment by CJY0208** [comment]
记录：非 CacheRoute 问题

问题原因：CacheRoute 里包裹了 Route 所致

4 里的 Route 没有使用新版上下文，所以更新是由上到下的，CacheRoute 那一层就阻止了更新，所以 4 里就算包了一个 Route 也能生效

但 5 里，Route 使用了新版上下文的 Consumer 进行内部更新，CacheRoute 无法再阻止，所以失效，Route 由内部取 Consumer 值自己更新，这个 CacheRoute 是没法下手管了的

解决方法

- 去除内部的 Route
- 将内部 Route 更换为 CacheRoute

用户如果使用嵌套路由的话，需要保证 CacheRoute 所在的那条链路，关键节点上都是 CacheRoute 才行，因为本身导致了卸载的原因就是 Route 默认的行为

**Comment by wangyinwei1** [comment]
请问react-activation在umi里使用会是不是不存在嵌套问题

**Comment by CJY0208** [comment]
@wangyinwei1 

react-activation 不存在嵌套问题
