### ISSUE TITLE
react-router-cache-route 能和umi结合下吗

### ISSUE THREAD

**Issue by johanazhu** [CJY0208/react-router-cache-route#47]
俊哥儿，react-router-cache-route 能和umi结合下吗？
或者给个思路

**Comment by Vision010** [comment]
你应该多看看umi的issues，umi已经对此做出了方案

**Comment by johanazhu** [comment]
没错，现在还没合并xiaohuoni 的分支

**Comment by CJY0208** [comment]
umi 的路由管理被包起来了，要使用 CacheRoute 的话只能等 umi 支持，在这之前如果想要即刻使用缓存功能，可以试试我新写的库 [react-activation](https://github.com/CJY0208/react-activation) 不依赖路由的 KeepAlive 方案，不需要等 umi 支持

**Comment by johanazhu** [comment]
好的，我试试看

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-cache-route

**Comment by CJY0208** [comment]
> https://www.npmjs.com/package/umi-plugin-cache-route

@johanazhu 推荐小火尼的渐进式方案

**Comment by xiaohuoni** [comment]
...@CJY0208 我不叫小火泥，我是小虎 oni

**Comment by CJY0208** [comment]
> ...@CJY0208 我不叫小火泥，我是小虎 oni

其实你已经介绍了遍插件，我又重复了，目的很明显，只是为了说一下这个给你起的外号~

顺便问一下，`umi keepalive` 的覆盖操作是不可逆的吗？

**Comment by xiaohuoni** [comment]
`umi keepalive` 覆盖操作不可逆，且是临时性的。重新安装任意模块，就会被重置。

**Comment by flyingFlowers** [comment]
使用云构建时，如何应用于生产环境
