### ISSUE TITLE
ts报错

### ISSUE THREAD

**Issue by XMBLDB** [CJY0208/react-router-cache-route#49]
"react-router-cache-route": "^1.8.1"
"@types/react": "16.4.18"
"typescript": "3.1.6"

1. CacheRoute设置when="always"时：
TS2322: Type '"always"' is not assignable to type 'When | ((props: CacheRouteProps) => boolean)'.
改为when={()=>true}就好；
2. TS2604: JSX element type 'CacheSwitch' does not have any construct or call signatures.

**Comment by ChangWenWu** [comment]
同样的问题，请问你解决了吗？

**Comment by CJY0208** [comment]
抱歉，因为我对 ts 不熟悉，可能 .d.ts 文件是有问题的，能否帮忙看一下可能是什么原因呀

或者考虑直接帮忙修正，十分感谢

我白天看一下

**Comment by CJY0208** [comment]
@XMBLDB @ChangWenWu 

v1.8.2 已经解决

之前对 CacheRoute 的 when 属性以及 CacheSwitch 的类型描述不正确
