### ISSUE TITLE
componentWillReceiveProps has been renamed Issue

### ISSUE THREAD

**Issue by xogns656** [CJY0208/react-router-cache-route#53]
Hi, Thanks for make this library.
Caching effectively work in my app.
But, repeatedly occur 'componentWillReceiveProps' warning in my app.
Warning is as follows : 
```
react-dom.development.js:12466 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: CacheComponent
```

I think present version using componentWillReceiveProps.
I hope to improve this Warning in the next version.
Thank you!

**Comment by CJY0208** [comment]
Got it and will fix it ~

May I know which version of React you are using ?

**Comment by CJY0208** [comment]
Past React version comparison is incorrect, fixed~ enjoy

**Comment by xogns656** [comment]
> Got it and will fix it ~
> 
> May I know which version of React you are using ?

Thanks for your reply comment!
I using React 16.10.2 version now.
And warning does not come out. 
it means your update good work in my app
