### ISSUE TITLE
在移动端safari浏览器上面返回出现问题

### ISSUE THREAD

**Issue by yuankai12** [CJY0208/react-router-cache-route#54]
进入到下层页面  滑动之后 点返回  上个页面滚动条位置丢失

**Comment by CJY0208** [comment]
CacheRoute 加上 saveScrollPosition="screen" 字段试试

**Comment by yuankai12** [comment]
帅哥  试了  没用   这个在android浏览器和web上是好的  就苹果设备的浏览器出现这个问题

**Comment by CJY0208** [comment]
好，我检查一下

**Comment by yuankai12** [comment]
好的  谢谢

**Comment by CJY0208** [comment]
查询了是由于 saveScrollPosition 函数仅操作了 document.documentElement 所致，在 safari 中应操作 document.scrollingElement

v1.8.3 已修复，可尝试

**Comment by yuankai12** [comment]
嗯嗯  谢谢

**Comment by CJY0208** [comment]
@yuankai12 我自个儿没有详细测试，如果修复了你的问题，可以的话也和我说一下哈！

**Comment by yuankai12** [comment]
@CJY0208 帅哥  还是有这个问题  麻烦你再看一下？

**Comment by yuankai12** [comment]
还是说 有些属性得加上去才能生效？

**Comment by CJY0208** [comment]
是的，CacheRoute 需要加上 saveScrollPosition 属性

```javascript
<CacheRoute ... saveScrollPosition />
```

**Comment by yuankai12** [comment]
![image](https://user-images.githubusercontent.com/45032697/68456986-25937180-023a-11ea-99f9-42fe65761e73.png)

这样对吗？

**Comment by CJY0208** [comment]
不用 ="screen" 直接 saveScrollPosition 就好啦

**Comment by CJY0208** [comment]
你的设备是什么型号的呢？iOS 版本是多少

**Comment by yuankai12** [comment]
iphone 11, ios 13.1.3

**Comment by CJY0208** [comment]
我做了一个在线 demo，可以试着用你的设备访问一下此处：https://t8f8e.csb.app/#/

完整 demo 为：https://codesandbox.io/s/cacheroute-online-demo-t8f8e

如果 demo 中对滚动行为表现正常，那问题可能在别处

**Comment by CJY0208** [comment]
我借用同事 iOS 13.1.3 尝试了是正常的

**Comment by yuankai12** [comment]
12.0没问题   13.1.3有问题   没用苹果的手势返回

**Comment by yuankai12** [comment]
这个问题已经处理完了  之前应该是因为升级版本了之后启动的时候  新版组件代码没有加载上造成的  谢谢
