### ISSUE TITLE
cacheKey自动设置为当前的url

### ISSUE THREAD

**Issue by xiongxt** [CJY0208/react-router-cache-route#58]
现在有一个路由/user/:id, 这个路由会打开很多页面，现在将他们缓存之后，怎么才能做到准确的删除其中某个缓存

**Comment by CJY0208** [comment]
OK，我看下怎么加这个功能，目前是 cacheKey 可以删掉同一个 Route 内的所有缓存，确实没有精确删除某一份的功能

**Comment by xiongxt** [comment]
我在调用了删除之后，马上调用查看缓存，发现缓存并没有被删除掉，这是异步删除的还是本身有bug呢？

**Comment by CJY0208** [comment]
是使用了 react 的 setState 功能，通知 CacheRoute 清空自身的缓存，存在一定的延时

**Comment by CJY0208** [comment]
v1.9.0 允许 cacheKey 传递函数，可以根据动态路由参数精确分配 cacheKey，可实现准确删除某一份缓存的功能

```jsx

<CacheRoute path="/item/:id" cacheKey={props => `/item/${props.match-params.id}`} ... />


dropByCacheKey('/item/1')

```

**Comment by 1101916341** [comment]
> 现在有一个路由/user/:id, 这个路由会打开很多页面，现在将他们缓存之后，怎么才能做到准确的删除其中某个缓存

您好，您是如何进行区分的啊，根据/:id，缓存不同的详情页数据，大佬能否指点一下
