### ISSUE TITLE
onchange method is cached. how to ignore.

### ISSUE THREAD

**Issue by chitgoks** [CJY0208/react-router-cache-route#60]
i have a function that is used in the onchange of an input field.

when the cacheroute goes to this component, it calls the async fetch method inside that function.

what i dont understand is it does call that async fetch when the function that has it is not even called.

is it possible to ignore cache on events?

**Comment by CJY0208** [comment]
can offer one simplest reproducible demo?

My understanding is like this below, seems to be right

```javascript

function SomeComponent() {
  
  const fetch = async () => {
    // do some aysnc tasks
  }

  return (
    <input onChange={fetch} />
  )
}

<CacheRoute ... component={SomeComponent} />

```

**Comment by chitgoks** [comment]
hi. i forgot what else i did after i submitted this issue. but it does not appear anymore :D ill close this one. thank you very much!
