### ISSUE TITLE
是否继续提供react-router-cache-route1.4.5版本的API?

### ISSUE THREAD

**Issue by jie0521** [CJY0208/react-router-cache-route#61]
在开发过程中使用react-router-cache-route1.4.5版本，但近期使用新版本1.8.2出现通过dropByCacheKey卸载不掉缓存组件的问题，现在只有1.8.0及以上的api，请问1.4.5版本的api是否继续提供？此外，新版本是否向前兼容？

**Comment by CJY0208** [comment]
向前兼容，若产生 breaking change 会更改大本本好，dropByCacheKey 依然保留，你遇到的可能是 bug，具体是什么情况？

**Comment by jie0521** [comment]
我们的业务场景是这样的：
从列表页跳转详情页时，先调dropByCacheKey 清除详情页的缓存，再进行跳转
目前的现象是：
如果使用react-router-cache-route1.4.5版本，跳转到详情页时，详情页 可以正常 向后台发请求
如果使用react-router-cache-route1.8.2版本，跳转到详情页时，详情页 没有 向后台发请求

**Comment by CJY0208** [comment]
这个问题是否和 #66 相同呢？

**Comment by jie0521** [comment]
相同
