### ISSUE TITLE
使用CacheRoute缓存页面，1.8.3版本手动清缓存，无法清除目标页缓存，1.4.5版本是可以的

### ISSUE THREAD

**Issue by jie0521** [CJY0208/react-router-cache-route#65]
项目中使用React15.2.1，react-router-dom4.0.0

页面A跳转页面B，在页面A中点击按钮时先手动清页面B的缓存再跳转，在使用react-router-cache-route的不同版本出现了不一样的现象：
1.8.3版本：
页面B的缓存没有清除，组件先后执行了如下声明周期函数 componentWillReceiveProps、componentWillUpdate、render、componentDidUpdate、didRecover

1.4.5版本：
页面B的缓存被清除，组件先后执行了如下声明周期函数 componentWillUnmount、constructor、componentWillUpdate、render、componentDidUpdate

**Comment by CJY0208** [comment]
问题是解决了吗？最近比较忙，还没看呢，怎么就关闭了呀

**Comment by CJY0208** [comment]
猜测也许是增加了多份缓存时影响了 dropByCacheKeys 功能，近期将尝试修复
