### ISSUE TITLE
cahceKey中存在点（如：cacheKey=“systemManager.powerManager.powerConfig”）导致使用dropByCacheKey方法无法手动清除组件缓存，

### ISSUE THREAD

**Issue by jie0521** [CJY0208/react-router-cache-route#66]
作者您好，缓存路由中的cacheKay属性中如果存在圆点，在使用dropByCacheKey方法手动清缓存时，发现组件的缓存没有清除掉。由于项目已经上线，在将react-router-cache-router版本由1.4.5升级到1.8.3发现此问题，麻烦作者帮忙看下如何解决
路由配置如下：
`<CacheRoute path="/systemManager/powerManager/powerConfig" cacheKey="systemManager.powerManager.powerConfig" when="always" component={PowerConfig}>`

**react-router-cache-router版本：**1.8.3
**在断点跟踪的过程中发现，如下源码中result的最终值为undefined**
`  var get = function get(obj) {
    var keys = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : [];
    var defaultValue = arguments[2];

    try {
      if (isNumber(keys)) {
        keys = String(keys);
      }
      **var result = (isString(keys) ? keys.split('.') : keys).reduce(function (res, key) {
        return res[key];
      }, obj);
      return isUndefined(result) ? defaultValue : result;**
    } catch (e) {
      return defaultValue;
    }
  };`
继续跟踪源码发现，如下代码中的cache值为undefined，代码不再继续向下执行直接跳出dropByCacheKey方法导致组件缓存没有卸载掉
`var dropByCacheKey = function dropByCacheKey(key) {
    var cache = get(__components, key);

    **if (!cache) {
      return;
    }**

    if (cache instanceof CacheComponent) {
      dropComponent(cache);
    } else {
      Object.values(cache).forEach(dropComponent);
    }
  };`

**Comment by CJY0208** [comment]
原来如此，因为 . 被识别为 get 方法的分隔标识了，大后天我处理一下

PS：get 方法为类似于 optional-chain api，也就是那个 a?.b?.c?.d，用来防止取值错误的

具体可以看这里 https://github.com/CJY0208/react-router-cache-route/blob/master/src/helpers/base/try/DOC.md

**Comment by jie0521** [comment]
好的  我先看一下，感谢~

**Comment by jie0521** [comment]
作者您好，关于我之前提出的这个问题，您目前修改了嘛？现在我们的cacheKey能否用 . 做分隔符？

**Comment by CJY0208** [comment]
@jie0521 

刚发布了 v1.8.4 修复了这个问题，谢谢 issue ~

**Comment by jie0521** [comment]
感谢
