### ISSUE TITLE
用HOC封装一层之后就没效果了

### ISSUE THREAD

**Issue by Jozdortraz** [CJY0208/react-router-cache-route#69]
` <CacheSwitch> <TestRoute path="/hello" component={TestComponent}/></CacheSwitch>`

`const TestRoute = ({
  component: Component,
  ...rest
}) => <CacheRoute {...rest} component={Component} />;`

这样就没效果了

**Comment by CJY0208** [comment]
试试 CacheSwitch 的 which 属性

https://github.com/CJY0208/react-router-cache-route#cacheswitch-props
