### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by juvconan** [CJY0208/react-router-cache-route#7]
/**
         * Only children prop of Route can help to control rendering behavior
         * 只有 Router 的 children 属性有助于主动控制渲染行为
         */
        React__default.createElement(reactRouterDom.Route, _extends({}, __rest__route__props, {
          children: function children(props) {
            return React__default.createElement(
              CacheComponent,
              _extends({}, props, { when: when, className: className, behavior: behavior }),
              function (cacheLifecycles) {
                return React__default.createElement(Updatable, {
                  match: props.match,
                  render: function render() {

                    Object.assign(props, { cacheLifecycles: cacheLifecycles });

                    if (component) {
                      return React__default.createElement(component, props);
                    }
我看源码中已经对Object.assign做了兼容处理，这边最后render函数里面的Object.assign为什么不使用_estends函数替代？我在低版本的浏览器运行时出现Object.assign is not a function错误

**Comment by CJY0208** [comment]
你好，考虑到目前的前端项目大多数都会自主选择垫片库，所以这个工具内没有考虑垫片库的处理，提前假设了执行环境是拥有垫片库的

当前碰到的问题需要你在自己的项目中引入一款垫片来解决，例如 [core-js](https://github.com/zloirock/core-js)

**Comment by EDSpower** [comment]
同问，怎么解决？

**Comment by CJY0208** [comment]
@EDSpower 引入一款垫片库
