### ISSUE TITLE
支持嵌套路由吗

### ISSUE THREAD

**Issue by laszhiai** [CJY0208/react-router-cache-route#70]
我项目中ABC三个路由，对应的path为/a,/b,/c，在A路由下又有子路/a/1,/a/2，使用的时候发现ABC是可以缓存的，但是/a/1,/a/2每次都会重新渲染

**Comment by CJY0208** [comment]
支持，但需要保证叶节点的 CacheRoute，其路径上的 Route 也都是 CacheRoute

处理起来比较麻烦，可以尝试 [react-activation](https://github.com/CJY0208/react-activation)

**Comment by CJY0208** [comment]
因为 CacheRoute 只能保证其本身，内部的组件在非命中路由时内部 display: none，但如果它自个儿被卸载了那就没办法了

**Comment by 806737859** [comment]
@CJY0208 嵌套路由，父路由（CacheRoute）A ，对应的component是一个（CacheSwtich）有子路由（CacheRoute）A1、（CacheRoute）A2，A1的path是/list，A2的path是/list/detal，从A1用Link跳转A2时，发现A对应的component被display:none了，怎么让A对应的组件不被影藏，因为该组件只是一个路由

**Comment by CJY0208** [comment]
@806737859 可以提供代码片段吗？我使用如下结构没有重现问题

```jsx
<CacheRoute path="/item">
  <CacheSwitch>
    <CacheRoute exact path="/item" component={Item} />
     <CacheRoute exact path="/item/2" component={Item2} />
  </CacheSwitch>
</CacheRoute>     
```

**Comment by 806737859** [comment]
@CJY0208 
父路由：
<CacheRoute path="/item" component={Item} >
</CacheRoute>    

父路由组件:
export default class Item extends React.Component {
    constructor(props) {
       super(props);
    }

    render() {
        return(
            <CacheSwitch>
                <CacheRoute exact path="/item" component={List} />
                <CacheRoute exact path="/item/detail" component={Detail} />
            </CacheSwitch>
        )
   }
}

// 子路由组件
export default class List  extends React.Component {
     ....
     <Link to={"/item/detail"} />
     ....
}

link跳转后，Detail组件被执行且被页面被渲染，但是，父路由组件被影藏，所以子路由组件间接被影藏

**Comment by CJY0208** [comment]
需要去掉父路由上的 exact 参数，这个参数是精确匹配的意思，仅在路由严格等于 /item 的时候才会命中

**Comment by 806737859** [comment]
@CJY0208  去掉了还是影藏

**Comment by CJY0208** [comment]
@806737859 可以把 demo 发过来看下，或者放在线上编辑器上，我帮忙排查问题

**Comment by 806737859** [comment]
@CJY0208 去掉了之后，父路由组件没有影藏，是子路由没有被渲染，我这是项目，没建demo

**Comment by CJY0208** [comment]
@806737859 需要注意是否是路由的使用方式不正确，目前应该不是 CacheRoute 的问题

**Comment by 806737859** [comment]
@CJY0208 能否提供一个详细的文档地址呢

**Comment by CJY0208** [comment]
> @CJY0208 能否提供一个详细的文档地址呢

这是 Router 的文档地址：https://reacttraining.com/react-router/

CacheRoute 是基于 Route 工作的，需要确保当前路径能命中 Route

**Comment by 806737859** [comment]
@CJY0208 好的，多谢
