### ISSUE TITLE
在移动端上面使用react-router-cache-route缓存插件，当我点击了详情页面的时候，在一次返回首页面的时候不会进行缓存，其他组件可以进行缓存

### ISSUE THREAD

**Issue by QiaokeliHenku** [CJY0208/react-router-cache-route#71]
### 求解答

import React, { Component} from "react";
// 引入react-router需要的一些路由组件
// import { Route, Switch, Router, Redirect } from "react-router-dom";
import { Switch, Route, Redirect } from "react-router-dom";
// 引入路由缓存的组件
// 引入路由配置文件
import config from './config'
import CacheRoute, { CacheSwitch } from "react-router-cache-route";
export default class RouterIndex extends Component {
    render() {
        return (
          // 我们在Switch组件当前去配置对应的路由映射表
          <CacheSwitch>
            {
            config.map((item, index) => {
              if (item.exact) {
                return (
                  <CacheRoute
                    exact={item.exact}
                    path={item.path}
                    component={item.component}
                    key={index}
                    when={"always"}
                    saveScrollPosition
                  />
                );
              } else {
                return (
                  <CacheRoute
                    path={item.path}
                    component={item.component}
                    key={index}
                    when={"always"}
                    saveScrollPosition
                  />
                );
              }
            })}
            <Redirect to="/home"></Redirect>
          </CacheSwitch>
        );
    }
}

**Comment by CJY0208** [comment]
没明白的你的意思，其他组件可以缓存指的是什么？其他页面吗？

代码中没看出来问题

**Comment by QiaokeliHenku** [comment]
其他页面是可以缓存的，但是我点击Home组件跳转到另一个页面的时候，在返回到Home组件那么Home组件就没有缓存

**Comment by QiaokeliHenku** [comment]
我在React插件当中是可以看到所有组件是被缓存的

**Comment by QiaokeliHenku** [comment]
我在React插件当中是可以看到所有组件是被缓存的

**Comment by QiaokeliHenku** [comment]
问题已解决
