### ISSUE TITLE
1.8.2版本在本地环境不生效；但是打包放到服务器是生效的

### ISSUE THREAD

**Issue by lianxiaozhuang** [CJY0208/react-router-cache-route#73]
react16.10.2
react-router-dom 5.1.2

**Comment by lianxiaozhuang** [comment]
import React from 'react';
import App from './App';
import ReactDOM from 'react-dom';
import store from './store/index'
import { Provider } from 'react-redux';
import * as serviceWorker from './serviceWorker';
import { AppContainer } from 'react-hot-loader';

import '@/config'
import '@/assets/css/index.scss';

ReactDOM.render(
    <AppContainer>
        <Provider store={store}>
            <App store={store} />
        </Provider>
    </AppContainer>
    ,
    document.getElementById('root')
);
serviceWorker.unregister();`
`

**Comment by lianxiaozhuang** [comment]
`import React from 'react';
import AllRoutes from './routes';
import { BrowserRouter as Router, Route, Switch, Redirect } from 'react-router-dom';

export default (props) => (
    <Router>
        <Switch>
            <Route exact path="/" render={() => <Redirect to="/home" push />} />    
            <Route path="/" render={()=> <AllRoutes store={props.store}  />} />
        </Switch>
    </Router>
)`

**Comment by lianxiaozhuang** [comment]
`
 <CacheSwitch>
 <CacheRoute
                                            {...routeParams}
                                      
                                            saveScrollPosition={true}
                                        />
 </CacheSwitch>
`

**Comment by Young-Wang** [comment]
遇到同样的问题，我只有在ios的safari上才生效。。

**Comment by lianxiaozhuang** [comment]
最新版本此问题已经fixed

**Comment by CJY0208** [comment]
神奇...我没对这个问题做修复，也许和不同环境中安装的依赖版本有关
@Young-Wang 同学你的还有问题吗？

**Comment by Young-Wang** [comment]
> 神奇...我没对这个问题做修复，也许和不同环境中安装的依赖版本有关
> @Young-Wang 同学你的还有问题吗？

我移除这个组件了，换成缓存数据去实现，没再去试这个

**Comment by CJY0208** [comment]
OK，那我关闭了
