### ISSUE TITLE
react-router 5.2.0 下报错

### ISSUE THREAD

**Issue by yesmeck** [CJY0208/react-router-cache-route#74]
react-router 5.2.0 不再导出 `__RouterContext` 了。

https://github.com/CJY0208/react-router-cache-route/blob/master/src/components/CacheSwitch.js#L7

**Comment by yesmeck** [comment]
建议发个仅支持 react-router 5 的 marjor 版本。

**Comment by CJY0208** [comment]
干掉了 __RouterContext 后，看起来只能使用 hook api 获取关键数据了，我先试下兼容

**Comment by CJY0208** [comment]
cache-route v1.9.0 版本兼容了 react-router-dom v5.2.0
