### ISSUE TITLE
关于拓展 cacheKey 可用性的讨论

### ISSUE THREAD

**Issue by a188658587** [CJY0208/react-router-cache-route#75]
抱歉小弟js学艺不精，源码没太看明白。
当设置multiple后，使用动态参数路由，getCachingKeys去拿到所有的缓存以路由名字为key的数组。
然后dropByCacheKey可以删除指定缓存。
目前只有设置cacheKey才能手动处理缓存。可否不设置cacheKey时，默认把路由地址做key。当设置multiple又设置了cacheKey，则返回 cacheKey_路由参数 的形式。
我想fork去改，可是有些地方看不懂。。。还望大神可以处理

**Comment by CJY0208** [comment]
项目可能会出现不同路由标签，但用了相同的路由地址的问题，如果默认 cacheKey 为路由地址，就会出现重复问题，因为 cacheKey  必须具有唯一性，而开发者又需要明确知道它的值是什么，所以并未设置默认逻辑

multiple 之下的组件 cacheKey 目前都相同，如果按 cacheKey 删除，会删除所有 multiple 路由下的缓存，暂不能精确删除 multiplt 中的某一份，这是个问题

我的想法是允许 cacheKey 传递 function 类型，接受 props 来动态生成 key，这样对于 cacheKey 上参数携带会更加灵活一些

```jsx
<CacheRoute path="/item/:id" cacheKey={props => `Item_${props.match.params.id}`} />
```

目前不计划加上默认 cacheKey 行为，在 cacheKey 允许传递 function 类型的基础上，但可以通过增加 defaultProps 配置来主动控制这一行为

```jsx
import { CacheRoute } from 'react-router-cache-route'

CacheRoute.defaultProps.cacheKey = props => props.location.pathname
```

也许可以缓解你的问题，如何？

**Comment by a188658587** [comment]
哇塞，果然厉害，说话逻辑都很清楚。
我fork这个项目了，简单的按照我的理解胡乱的改了改。
您说的这个很不错，而且也更灵活，兼容性也好。
期待您的更新！

**Comment by CJY0208** [comment]
cache-route v1.9.0 版本允许 cacheKey 传递 function 类型，可以试试能否满足需求，此 issue 先关闭，有问题再重开啦~

**Comment by a188658587** [comment]
棒棒的！
