### ISSUE TITLE
react-router-dom5.1.2报错

### ISSUE THREAD

**Issue by 793922039** [CJY0208/react-router-cache-route#77]
没拿到router，报TypeError: Cannot read property 'route' of undefined
https://github.com/CJY0208/react-router-cache-route/blob/41e51771b61c27fe57f2afc3da468a6a40df4338/dist/cacheRoute.js#L971
不知道什么原因引起的，崩溃呀

**Comment by 793922039** [comment]
没拿到router

**Comment by CJY0208** [comment]
可能与 #74 相同，react-router-dom 升到 5.2.0 之后不再暴露 __RouterContext 所致，待修正

**Comment by 793922039** [comment]
嗯，标题说错了，是5.2.0报错，降版本之后可以了。但是遇到个问题，我的项目中有个需求是一级路由跳到二级路由的时候页面是从右滑入的，而一级路由的页面是不隐藏的。我设置了behavior来控制缓存时的样式，但是第一次跳二级路由的时候一级路由的页面会闪一下，之后就不会闪了

**Comment by CJY0208** [comment]
cache-route v1.9.0 版本兼容了 react-router-dom v5.2.0
此 issue 需要关闭，如果上述现象确认是 cache-route 所致，需要新开一个 issue 讨论啦~
