### ISSUE TITLE
ios上路由跳转页面缓存数据丢失，滚动条高度不能缓存，结合mobx使用的

### ISSUE THREAD

**Issue by lize9791** [CJY0208/react-router-cache-route#81]
离开当前页面，返回来的时候滚动条高度有时候可以缓存，有时候不行，而且滑到上面那部分的数据会丢失，不能上滑，保存的一些数据也会清除，安卓没问题，ios有问题

**Comment by CJY0208** [comment]
沟通后为写法问题，已解决，closed
