### ISSUE TITLE
您好，大佬，我想问下，dropByCacheKey()方法不能传入多个参数吗？

### ISSUE THREAD

**Issue by 1101916341** [CJY0208/react-router-cache-route#85]

**Comment by 1101916341** [comment]
如果能够传入的话，如何操作啊？求大佬帮忙解答一下，万分感谢

**Comment by CJY0208** [comment]
目前不能传入多个参数，是希望同时清空多个缓存吗？可以用循环包装一下

```js

const dropMultiple = keys => keys.forEach(key => dropByCacheKey(key))
···

**Comment by 1101916341** [comment]
> 目前不能使用多个参数，是希望同时清空多个缓存吗？可以用循环包装一下
> 
> ```js
> const  dropMultiple  =  keys  =>  keys 。forEach （键 =>  dropByCacheKey （键））
> 
> dropMultiple （[ 'key1' ， 'key2' ， 'key3' ] ）
> ```

是的，想同时清空多个缓存，谢谢大佬，我和您想的一样，进行遍历操作
