### ISSUE TITLE
路由使用 lazy，缓存就会无效

### ISSUE THREAD

**Issue by niubilityWly** [CJY0208/react-router-cache-route#87]
问题：路由中如果用 Suspense 包裹了页面，缓存就不生效了，这是为什么呢？

代码：

~~~Jsx
import React, { Component, lazy, Suspense } from 'react'
const Test = lazy(() => import('./Test'))

function WaitingComponent(Component) {
  return props => (
    <Suspense fallback={<div>Loading...</div>}>
      <Component {...props} />
    </Suspense>
  );
}

<HashRouter>
   <CacheSwitch>
      <CacheRoute 
          when="always" 
          exact 
          path="/Test" 
          component={WaitingComponent(Test)}
      />
   </CacheSwitch>
</HashRouter>
~~~

**Comment by CJY0208** [comment]
component 重复定义所致，尝试改成


const _Test = WrapperComponent(Test)


<CacheRoute ... component={_Test} /&gt;


避免在 component 赋值时重复创建组件定义



---原始邮件---
发件人: "niubilityWly"<notifications@github.com&gt;
发送时间: 2020年9月7日(周一) 晚上7:03
收件人: "CJY0208/react-router-cache-route"<react-router-cache-route@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [CJY0208/react-router-cache-route] 路由使用 lazy，缓存就会无效 (#87)




 
问题：路由中如果用 Suspense 包裹了页面，缓存就不生效了，这是为什么呢？
 
代码：
 import React, { Component, lazy, Suspense } from 'react' const Test = lazy(() =&gt; import('./Test')) function WaitingComponent(Component) {   return props =&gt; (     <Suspense fallback={<div&gt;Loading...</div&gt;}&gt;       <Component {...props} /&gt;     </Suspense&gt;   ); } <HashRouter&gt;    <CacheSwitch&gt;       <CacheRoute            when="always"            exact            path="/Test"            component={WaitingComponent(Test)}       /&gt;    </CacheSwitch&gt; </HashRouter&gt;

**Comment by CJY0208** [comment]
component 重复定义所致，尝试改成


```jsx
const _Test = WaitingComponent(Test)

<CacheRoute ... component={_Test} />
```

组件的重复定义会造成渲染实例差异，也就是代码虽相同，但本质上是两个完全不同的组件，也就无从谈及状态保存

造成的现象就是看起来缓存失效了，需要避免在 component 赋值时重复创建组件定义，以避免此问题
