### ISSUE TITLE
关于CacheRoute，能否在匹配路由时，动态确定是否加载缓存？

### ISSUE THREAD

**Issue by dabenlu803** [CJY0208/react-router-cache-route#9]
目前开发的后台管理系统界面，采用tab标签管理多个打开的页面，加载页面有以下几种：
1.点击侧边菜单，或者tab页之间切换时，需要加载已缓存的相同路由页面。
2.当打开某项数据的详情页或编辑页时，需要打开全新的页面，而非缓存页面。

能否增加一个机制，可以动态控制匹配路由时，应加载缓存还是不加载缓存页面呢？

**Comment by dabenlu803** [comment]
系统使用场景介绍：
1.点击左侧菜单项，右侧内容区域打开一个tab页显示该菜单对应的内容页。
2.如果菜单项首次点击，新增一个tab，并打开一个新的内容页（内容是非缓存的）。
3.如果菜单项非首次点击，tab切换至对应内容页（内容是缓存的）。
4.点击各tab标题，可以切换至对应内容页（内容是缓存的）。
5.关闭tab页，对应内容页销毁，再次点击菜单栏打开该内容页时，数据为最新内容。

请问下如果要满足上述使用场景，是否只能用缓存生命周期 didRecover 来处理数据更新的事宜？

**Comment by CJY0208** [comment]
@dabenlu803 你好！最近一直比较忙，很抱歉现在才增加了你期望的新功能，另外，感谢反馈！~

v1.3.0 中增加了 dropByCacheKey 功能，可以命令式的方式清除缓存

具体参考：
https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md#%E6%89%8B%E5%8A%A8%E6%B8%85%E9%99%A4%E7%BC%93%E5%AD%98
