### ISSUE TITLE
H5移动端兼容问题

### ISSUE THREAD

**Issue by TerryMinH** [CJY0208/react-router-cache-route#91]
父级页面分页的长列表进入子页面并配置了路由缓存，然后在返回父级页面更新长列表数据分页请求；浏览器模拟器没问题，在移动端浏览器中只能请求第一页数据，这个是什么原因呢？谢谢
![image](https://user-images.githubusercontent.com/50506523/97246676-db374600-1838-11eb-922b-8e338aa807e2.png)

**Comment by CJY0208** [comment]
沟通后暂定非 cache-route 兼容性问题，可能为 antd ListView 组件 onEndReached 触发问题所致，暂时关闭
