### ISSUE TITLE
globalThis.js uses unsafe eval

### ISSUE THREAD

**Issue by s3curitybug** [CJY0208/react-router-cache-route#92]
https://github.com/CJY0208/react-router-cache-route/blob/497c32145ab51b3a77b753a101bea357325a20aa/src/helpers/base/globalThis.js#L12

This line uses Function(), which gets blocked when used with Content Security Policy unless unsafe-eval is used.

**Comment by CJY0208** [comment]
It‘s from globalThis polyfill: https://github.com/es-shims/globalThis/blob/master/implementation.browser.js

Does it crash your project?

The polyfill from tc39 throw an error when the program reaches that position, looks more standardized
https://github.com/tc39/proposal-global#rationale

**Comment by s3curitybug** [comment]
The browser blocks the script if Content Security Policy is used.

![image](https://user-images.githubusercontent.com/26045270/97516859-5c572000-1994-11eb-8d85-c7f1619c9084.png)

In my case, I bundle everything in just one js, so all my project gets blocked because of that line.

**Comment by CJY0208** [comment]
try v1.10.1

**Comment by s3curitybug** [comment]
Works like a charm. Thank you!

**Comment by CJY0208** [comment]
OK, closed~
