### ISSUE TITLE
配合redux使用的时候会报错

### ISSUE THREAD

**Issue by bihongbin3027** [CJY0208/react-router-cache-route#93]
![image](https://user-images.githubusercontent.com/15045200/98210584-be5aeb00-1f7b-11eb-8e16-3c03ee3fb61a.png)
![image](https://user-images.githubusercontent.com/15045200/98210680-e4808b00-1f7b-11eb-9512-83751b748fb2.png)

**Comment by bihongbin3027** [comment]
Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement

**Comment by CJY0208** [comment]
看起来是 hooks 使用的问题，应该与 cache-route 本身无关

**Comment by bihongbin3027** [comment]
是我使用的有问题
