### ISSUE TITLE
Caching route with querystring

### ISSUE THREAD

**Issue by carlospence** [CJY0208/react-router-cache-route#95]
I have a route that can either have a querystring or not. If there is no querystring, the route is cached but the moment there is a querystring, there is always a reload when navigating back to it.

https://192.168.0.100:3000/dashboard/group/prospectspage?labelType=District1 (Always reloading)
https://192.168.0.100:3000/dashboard/group/prospectspage (Always caching)

I did something like this in building my routes

 ```
<CacheSwitch>
            {routes.map((route, idx) => {
              if (route.name === "GroupProspects" || route.name === "Prospects")
              {
                return route.component && (
                  <CacheRoute
                    cacheKey={route.name}
                    when={"always"}
                    saveScrollPosition={true}
                    key={idx}
                    path={route.path}
                    exact={route.exact}
                    name={route.name}
                    render={props => (
                        <route.component {...props} />
                    )} />
                )
              }
              return route.component && (
                <Route
                  key={idx}
                  path={route.path}
                  exact={route.exact}
                  name={route.name}
                  render={props => (
                      <route.component {...props} />
                  )} />
              )
            })}
            <Redirect from="/" to="/dashboard" />
          </CacheSwitch>
```
How can I cache a path with querystring. I used querystring instead of something like this "https://192.168.0.100:3000/dashboard/group/prospectspage/labelType" because, I can have multiple querystrings.

**Comment by CJY0208** [comment]
try to use `multiple` prop on `CacheRoute` like this:

```jsx
<CacheRoute mutiple ... />
```

https://github.com/CJY0208/react-router-cache-route#cacheroute-props

**Comment by carlospence** [comment]
Still not caching

**Comment by carlospence** [comment]
I had to finally use url parameters instead of querystring before getting it to work
