### ISSUE TITLE
Provide hooks for life cycle methods

### ISSUE THREAD

**Issue by ali-garajian** [CJY0208/react-router-cache-route#97]
Hey there, thanks a lot for the great package!
I'm using a custom hook to control my app's loading state, which needs access to the "didCache" life cycle method to set the loading state to false whenever the component is cached. Right now there's a lot of duplicate code in all my pages, just passing the methods down to my custom hook and using it there. 
I was wondering if you could expose a "useCacheLifecycles" which would return "didCache" and "didRecover"?

**Comment by CJY0208** [comment]
sure, soon

**Comment by CJY0208** [comment]
try v1.11.0 with `useDidCache` and `useDidRecover`

[README](https://github.com/CJY0208/react-router-cache-route#hooks) updated

```jsx
import { useDidCache, useDidRecover } from 'react-router-cache-route'

export default function List() {

  useDidCache(() => {
    console.log('List cached 1')
  })

  // support multiple effect
  useDidCache(() => {
    console.log('List cached 2')
  })

  useDidRecover(() => {
    console.log('List recovered')
  })

  return (
    // ...
  )
}
```
